Changes in Multilayer classes after XPS tests
Pazus/ESCal pull request #5
Opened 2018-03-02 08:53 UTC by olry

2018-03-02 10:26 UTC, Pazus requested changes

2018-03-02 10:26 UTC, Pazus commented on src/lib/ELF/Drude.m
> +        eps_re(w_global<w_at_q,:)=0;
Look through the Vos article, peak position for Drude function is not there. It’s somwhat like `sqrt(A+wp^2)`

2018-03-12 19:30 UTC, olry commented
Pavel, add this pullrequest

2018-03-14 06:51 UTC, Pazus requested changes
Please check throughout the changes for misuses of `bsxfun`. 
If you need element wise power use `omega0.^2`. Remember that all operations between a matrix and a scalar are also elementwise producing result of the matrix size.
The only situation where you need to use `bsxfun` is when you need to perform an operation on column-vector versus row-vector and expect a matrix as the result.

Unfortunately `bsxfun` makes code much harder to read, so we need to reduce its appearance as much as possible.

2018-03-14 06:51 UTC, Pazus commented on src/lib/ELF/eps_sum.m
> +            ind = bsxfun(@ne,epsMerm,0);
Здесь не нужен bsxfun, достаточно просто `epsMerm~=0`

2018-03-14 06:51 UTC, Pazus commented on src/CalculationClasses/MultiLayer/BaseMultiLayer.m
>              if ~obj.IsCalculated; error('Not calculated yet.'); end;
Почему так? Это же повлияет на все ранее сделанные расчёты!

2018-04-04 15:22 UTC, Pazus approved these changes

2018-04-04 15:22 UTC, merged